blank_issues_enabled: true
contact_links:
  - name: General
    url: https://github.com/umitkayikcioglu/poyraz/discussions/new?category=general
    about: Want to discuss something?
  - name: Ideas
    url: https://github.com/umitkayikcioglu/poyraz/discussions/new?category=ideas
    about: Want to suggest an idea?
  - name: Questions
    url: https://github.com/umitkayikcioglu/poyraz/discussions/new?category=q-a
    about: Have a question?
